# h2 database web console
spring:
    datasource:
        url: jdbc:h2:mem:test;MODE=MySQL;
        username: sa
        password:
        driver-class-name: org.h2.Driver
        generate-unique-name: false
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    h2:
        console:
            enabled: true
            path: /h2-console
    sql:
        init:
            mode: embedded
#            schema-locations: classpath:schema.sql
#            data-locations: classpath:data.sql
