CREATE TABLE reservation_info
(
	id         BIGINT AUTO_INCREMENT PRIMARY KEY,
	start_at   TIMESTAMP NOT NULL,
	end_at     TIMESTAMP NOT NULL,
	created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
